app:
  name: launchpad-ui
  namespace: delivery-launchpad
  component: ui

container:
  image: "<Docker Repo>/launchpad-ui"
  tag: "latest"
  pullPolicy: Always
  port: 8080
  resources:
    requests:
      cpu: 500m
      memory: 2Gi
    limits:
      cpu: 1000m
      memory: 4Gi

deploy:
  replica: 2
  subfix: ""
  rollingupdate:
    maxSurge: 1
    maxUnavailable: 1
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: <Selector Key>
                operator: In
                values:
                  - <Selector Value>
ingress:
  hostname:
  - localhost
  path: /
  class: delivery-ingress
