app:
  name: launchpad-api
  namespace: delivery-launchpad
  component: api
  profile: prod

container:
  image: "<Docker Repo>/launchpad-api"
  tag: "latest"
  pullPolicy: Always
  port: 8080
  resources:
    requests:
      cpu: 4
      memory: 4Gi
    limits:
      cpu: 8
      memory: 4Gi

deploy:
  replica: 3
  subfix: ""
  rollingupdate:
    maxSurge: 1
    maxUnavailable: 1
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: <Selector Key>
                operator: In
                values:
                  - <Selector Value>

ingress:
  hostname:
  - localhost
  path: /launchpad-api
  class: delivery-ingress

minio:
  access_key_id: <ACCESS_KEY>
  secret_access_key: <SECRET_KEY>
  bucket_name: mlflow
  endpoint_url: http://minio.vip.hnd1.bdd.local:9000

mlflow:
  server_uri: http://launchpad-mlflow.delivery-launchpad.svc.cluster.local:5000

